### ISSUE TITLE
How can I use this as a "base image"?

### ISSUE THREAD

**Issue by rohanshiva** [hb2638/aws_lambda_python_3.11#1]
My intention is to use this as a base layer, and the upload my src code via zip. Is there any way to achieve this? Or is the only option to build a container image using this as the base in the Dockerfile, and upload to lambda via ECR?

**Comment by hb2638** [comment]
There’s really no other way, sorry. I’m in the same boat.
 But, you can have a lambda image with a superset of all your requirements/packages to reduce the number of docker images you need to deploy. This won’t work if you need different versions of the same package.
